Revert "update to v0.6.1"
This reverts commit 0803893b402e9b4930e961a86986b9a9858d6931.

diff --git a/deb-peercoin/debian/rules b/deb-peercoin/debian/rules
--- a/deb-peercoin/debian/rules
+++ b/deb-peercoin/debian/rules
@@ -1,64 +1,122 @@
 #!/usr/bin/make -f
-# -*- mode: makefile; coding: utf-8 -*-
+# Sample debian/rules that uses debhelper.
+# GNU copyright 1997 to 1999 by Joey Hess.
 
-#DEB_INSTALL_EXAMPLES_ppcoind += debian/examples/*
-#DEB_INSTALL_MANPAGES_ppcoind += debian/manpages/*
+# Uncomment this to turn on verbose mode.
+#export DH_VERBOSE=1
 
 # Hardening
 export DEB_BUILD_HARDENING=1
 export DEB_BUILD_MAINT_OPTIONS=hardening=+all
+include /usr/share/hardening-includes/hardening.make
 CFLAGS=$(shell dpkg-buildflags --get CFLAGS)
 LDFLAGS=$(shell dpkg-buildflags --get LDFLAGS)
 CFLAGS+=$(HARDENING_CFLAGS)
 LDFLAGS+=$(HARDENING_LDFLAGS)
 
-NAME=peercoin
+USE_QR=$(shell if [ -r /usr/include/qrencode.h ]; then echo USE_QRCODE=1; fi)
+NAME=ppcoin
+#DESTDIR=/usr/src/packages/BUILD/debian/$(NAME)
 DESTDIR=debian/$(NAME)
 PREFIX=/usr
+BINDIR=$(PREFIX)/bin
 LIBDIR=$(PREFIX)/lib
-BINDIR=$(PREFIX)/bin/
-DATADIR=$(PREFIX)/share/
+SBINDIR=$(PREFIX)/sbin
+MANDIR=$(PREFIX)/share/man
+DATADIR=$(PREFIX)/share
+DOCDIR=$(PREFIX)/share/doc/$(NAME)
+SYSCONFDIR=/etc
 RCDIR=$(LIBDIR)/systemd/system/
+CGIDIR=/src/www/cgi-bin
 
-%:
-	dh $@
+build: build-arch build-indep
+build-arch: build-stamp
+build-indep: build-stamp
+build-stamp:
+	dh_testdir
 
-override_dh_auto_build:
-	
-	# patches
-	patch share/genbuild.sh < SOURCES/genbuild.patch
+	# Compile
 
-	$(MAKE) -C src/ -f makefile.unix $(NAME)d USE_UPNP=1
-	$(MAKE)
+	patch share/genbuild.sh < ../SOURCES/genbuild.patch
+	patch src/version.cpp < ../SOURCES/version_id.patch
 
-override_dh_auto_clean:
-	if [ -f Makefile ]; then $(MAKE) clean; else rm -rf build/; rm -f $(NAME); fi
-	cd src; $(MAKE) -f makefile.unix clean
+	qmake $(USE_QR) USE_DBUS=1 USE_UPNP=1 USE_SSL=1
+	make
+	strip $(NAME)-qt
+	make -C src -f makefile.unix USE_UPNP=1 USE_SSL=1
+	strip src/$(NAME)d
+	# --- end custom part for compiling
 
-override_dh_auto_configure:
-	qmake bitcoin-qt.pro USE_QRCODE=1 USE_DBUS=1
+	touch build-stamp
 
-override_dh_auto_install:
+clean:
+	dh_testdir
+	dh_testroot
+	rm -f build-stamp
 
+	# Add here commands to clean up after the build process.
+	make clean || true
+	make -C src -f makefile.unix clean
+	rm -f src/Makefile
+	# --- end custom part for cleaning up
+
+	dh_clean
+
+install: build
+	dh_testdir
+	dh_testroot
+	dh_prep
+	dh_installdirs
+
+	# Add here commands to install the package
+	# The DESTDIR Has To Be Exactly  /usr/src/packages/BUILD/debian/<nameOfPackage>
 	mkdir -p "$(DESTDIR)$(BINDIR)"
 	install -m 0755 $(NAME)-qt "$(DESTDIR)$(BINDIR)"
 	install -m 0755 src/$(NAME)d "$(DESTDIR)$(BINDIR)"
 
 	mkdir -p "$(DESTDIR)$(RCDIR)"
-	install -m 644 "SOURCES/$(NAME)d@.service" "$(DESTDIR)$(RCDIR)"
-	install -m 644 "SOURCES/$(NAME)d-tor@.service" "$(DESTDIR)$(RCDIR)"
-	install -m 644 "SOURCES/$(NAME)-qt@.service" "$(DESTDIR)$(RCDIR)"
-	install -m 644 "SOURCES/$(NAME)-qt-tor@.service" "$(DESTDIR)$(RCDIR)"
+	install -m 644 "../SOURCES/$(NAME)d@.service" "$(DESTDIR)$(RCDIR)"
+	install -m 644 "../SOURCES/$(NAME)d-tor@.service" "$(DESTDIR)$(RCDIR)"
+	install -m 644 "../SOURCES/$(NAME)-qt@.service" "$(DESTDIR)$(RCDIR)"
+	install -m 644 "../SOURCES/$(NAME)-qt-tor@.service" "$(DESTDIR)$(RCDIR)"
 	mkdir -p "$(DESTDIR)$(DATADIR)/applications"
-	install -m 644 "contrib/debian/$(NAME)-qt.desktop" "$(DESTDIR)$(DATADIR)/applications"
+	install -m 644 "../SOURCES/$(NAME).desktop" "$(DESTDIR)$(DATADIR)/applications"
 	mkdir -p "$(DESTDIR)$(DATADIR)/pixmaps"
-	install -m 644 src/qt/res/icons/$(NAME).png "$(DESTDIR)$(DATADIR)/pixmaps"
+	install -m 644 src/qt/res/icons/ppcoin.png "$(DESTDIR)$(DATADIR)/pixmaps"
+	# --- end custom part for installing
 
-override_dh_auto_test:
-	cd src; $(MAKE) -f makefile.unix test_${NAME}
-	src/test_${NAME}
+# Build architecture-independent files here.
+binary-indep: build install
+	# We have nothing to do by default.
 
-.PHONY: override_dh_strip
-override_dh_strip:
-	dh_strip ${NAME}-qt
-	dh_strip src/${NAME}d
+# Build architecture-dependent files here.
+binary-arch: build install
+	dh_testdir
+	dh_testroot
+#	dh_installdebconf
+	dh_installdocs COPYING doc/README
+#	dh_installexamples
+	dh_installmenu
+#	dh_installlogrotate
+#	dh_installemacsen
+#	dh_installpam
+#	dh_installmime
+#	dh_installinit
+#	dh_installcron
+#	dh_installman
+	dh_installinfo
+#	dh_undocumented
+	dh_installchangelogs
+	dh_link
+	dh_compress
+	dh_fixperms
+#	dh_makeshlibs
+	dh_installdeb
+#	dh_perl
+	dh_shlibdeps
+	dh_gencontrol
+	dh_md5sums
+	dh_builddeb
+
+binary: binary-indep binary-arch
+.PHONY: build clean binary-indep binary-arch binary install
